---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(tidytext)
library(curl)
library(data.table)
library(dplyr)
library(DT)
library(forcats)
library(ggplot2)
library(ggridges)
library(ggthemes)
library(haven)
library(htmltools)
library(httr)
library(janitor)
library(jsonlite)
library(knitr)
library(knitLatex)
library(magrittr)
library(plotly)
library(readr)
library(readxl)
library(reshape2)
library(rvest)
library(stringr)
library(tools)
library(viridisLite)
library(viridis)
```


```{r cache = TRUE}
restaurant_inspections = read_csv("DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Distributions of inspection scores by borough


```{r}
restaurant_inspections %>%
  group_by(boro) %>%
  plot_ly(y = ~score, color = ~boro, type = "box") 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Inspection grade frequency by borough
```{r}
restaurant_inspections %>%
  group_by(boro) %>%
  count(grade) %>%
  ungroup() %>%
  mutate(boro = fct_reorder(boro, n)) %>%
  plot_ly(x = ~boro, y = ~n, color = ~grade, type = "bar")
```

### Inspection score over time by restaurant

```{r}
restaurant_inspections %>%
  group_by(camis) %>%
  filter(!duplicated(inspection_date)) %>%
  select(camis, inspection_date, score) %>%
  plot_ly(x = ~inspection_date, y = ~score, group_by = ~camis,
            type = 'scatter', 
            alpha = 0.25,
            mode = 'lines+markers') %>%
  layout(xaxis = list(range = c(as.Date('2012-01-01'), as.Date('2019-01-01'))))
```

